#!/usr/bin/env bash
# Script that installs Nginx server and add a custom header
apt-get -y update
apt-get -y install nginx
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By $hostname;/" /etc/nginx/sites-available/default
service nginx restart
