#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
apt-get -y update
apt-get -y upgrade
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update
apt-get -y install haproxy=2.5.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 7617-web-01 44.211.27.133:80 check\n\tserver 7617-web-02 3.85.241.255:80 check" >> /etc/haproxy/haproxy.cfg
service nginx stop
service haproxy restart
